version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run build-webpack

artifacts:
  files:
    - index.html
    - blog.html
    - portfolio.html
    - favicon.ico
    - images/*
    - dist/app.js
    - dist/vendor.js
    - dist/styles.css
