version: 0.1

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build-webpack

artifacts:
  files:
    - index.html
    - blog.html
    - portfolio.html
    - favicon.ico
    - images/*
    - dist/bundle.js
    - dist/styles.css
